FROM debian:bookworm-slim

ARG CMDLINE_TOOLS_PKG=commandlinetools-linux-13114758_latest
ARG BUILD_TOOLS=34.0.0
ENV DEBIAN_FRONTEND=noninteractive

ENV ANDROID_HOME=/opt/android
ENV ANDROID_SDK_ROOT=$ANDROID_HOME
ENV ANDROID_AVD_HOME=/opt/avd
ENV PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator
ENV EMULATOR_DEFAULT_ARGS="-no-window -no-audio -no-boot-anim -gpu swiftshader_indirect -accel on -camera-back none -timezone Europe/Berlin"
ENV HOME=/root
ENV ANDROID_API=36

WORKDIR /tmp

RUN apt-get update && apt-get install -y --no-install-recommends \
    bash ca-certificates git unzip wget curl \
    lib32stdc++6 lib32z1 libc6-i386 \
    libglu1-mesa libpulse0 libxi6 libxrender1 libxrandr2 libxcomposite1 libxcursor1 libxinerama1 \
    libnss3 libx11-6 libxcb1 libdbus-1-3 libgl1 libgl1-mesa-dri \
    openjdk-17-jre-headless kmod udev procps \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN wget -qO cmdline-tools.zip "https://dl.google.com/android/repository/${CMDLINE_TOOLS_PKG}.zip" \
 && mkdir -p "$ANDROID_HOME/cmdline-tools/latest" \
 && unzip -q cmdline-tools.zip -d "$ANDROID_HOME/cmdline-tools/temp" \
 && mv "$ANDROID_HOME/cmdline-tools/temp/cmdline-tools/"* "$ANDROID_HOME/cmdline-tools/latest/" \
 && rm -rf "$ANDROID_HOME/cmdline-tools/temp"

ENV SYS_A="system-images;android-36;google_apis;x86_64"
ENV SYS_B="system-images;android-36;google_apis_playstore;x86_64"
RUN yes | sdkmanager --licenses \
 && ( yes | sdkmanager --install \
        "platform-tools" "emulator" "build-tools;${BUILD_TOOLS}" \
        "platforms;android-36" "${SYS_A}" \
      || yes | sdkmanager --install \
        "platforms;android-36" "${SYS_B}" ) \
 && yes | sdkmanager --update \
 && rm -rf /root/.android /tmp/*

RUN mkdir -p "$ANDROID_AVD_HOME" "$HOME/.android" \
 && IMG="$SYS_A"; if [ ! -d "$ANDROID_HOME/$(echo $SYS_A | sed 's#;#/#g')" ]; then IMG="$SYS_B"; fi \
 && ANDROID_AVD_HOME="$ANDROID_AVD_HOME" yes "no" | avdmanager create avd \
      -n base-avd -k "$IMG" --abi x86_64 --device "pixel_5" --sdcard 256M --force \
 && printf '%s\n' \
      'hw.cpu.ncore=2' \
      'hw.gpu.enabled=yes' \
      'hw.gpu.mode=swiftshader_indirect' \
      'hw.keyboard=yes' \
      'skin.dynamic=yes' \
      'fastboot.forceColdBoot=yes' \
      'hw.ramSize=4096' \
      'vm.heapSize=640' \
      >> "$ANDROID_AVD_HOME/base-avd.avd/config.ini" \
 && rm -rf /root/.android /tmp/*

COPY start-emulator.sh /opt/start-emulator.sh
COPY stop-emulator.sh  /opt/stop-emulator.sh
RUN chmod +x /opt/start-emulator.sh /opt/stop-emulator.sh

RUN printf '%s\n' \
'#!/usr/bin/env bash' \
'set -e' \
'if [ -e /dev/kvm ]; then chmod 666 /dev/kvm || true; fi' \
'exec "$@"' > /usr/local/bin/with-kvm && chmod +x /usr/local/bin/with-kvm

WORKDIR /workspace
CMD ["bash"]
